services:
  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
  backend:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    restart: unless-stopped
  mongodb:
    image: mongo:8.0
    ports:
      - 37017:27017
    volumes:
      - ./data:/data/db
    restart: unless-stopped
